name: iOS-Android-Build

on:
  workflow_dispatch:

jobs:
  build-ios-android:
    name: 🎉 iOS and Android Build
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Step 3: Get Flutter dependencies
      - name: Install Flutter packages
        run: flutter pub get

      # Step 4: Install CocoaPods dependencies for iOS
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          pod repo update

      # Step 5: Build iOS release (no codesign)
      - name: Build iOS release without code signing
        run: flutter build ios --release --no-codesign

      # Step 6: Prepare .ipa structure
      - name: Create Payload folder for .ipa
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app to Payload
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Step 7: Zip Payload to create .ipa file
      - name: Zip .ipa file
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Step 8: Build Android APK
      - name: Build Android APK
        run: flutter build apk --release

      # Step 9: Upload the .ipa file and .apk file as release assets
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            build/ios/iphoneos/FlutterIpaExport.ipa
            build/app/outputs/flutter-apk/app-release.apk
          tag: v1.0
          overwrite: true
          body: "This is the first release, including both iOS and Android builds."
